version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # <-- Оставляем только пароль для root
      MYSQL_DATABASE: my_database    # <-- Опционально создаёт БД при старте
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
